import streamlit as st
from PIL import Image
import pytesseract
import pypdf
import os
import re
import io

# --- Tesseract Configuration (IMPORTANT for Windows/Custom setups) ---
# If Tesseract is not in your system's PATH, you need to specify its location.
# pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'
# Uncomment and modify the line below if needed:
# pytesseract.pytesseract.tesseract_cmd = r'/path/to/tesseract' 

# --- Language Mappings for Streamlit Selector ---
# IMPORTANT: For non-English languages, you must have the corresponding 
# Tesseract language data files (.traineddata) installed.
LANGUAGE_MAP = {
    "English": "eng",
    "Spanish": "spa",
    "French": "fra",
    "German": "deu",
    "Italian": "ita",
    "Portuguese": "por",
    "Auto-Detect (Default)": "eng"  # Tesseract defaults to 'eng' but can auto-detect
}

## --- Core Text Cleaning Function ---

def clean_extracted_text(text):
    """
    Performs basic cleanup on OCR text to improve readability.
    - Removes common OCR artifacts (form feeds, vertical tabs).
    - Replaces multiple newlines/spaces with single ones.
    - Strips leading/trailing whitespace.
    """
    # 1. Remove form feed characters and vertical tabs often generated by OCR
    text = re.sub(r'\f', ' ', text)
    text = re.sub(r'\v', ' ', text)
    
    # 2. Clean up common non-ASCII characters that result from poor OCR
    text = re.sub(r'[^\x00-\x7F]+', ' ', text) 
    
    # 3. Replace multiple newlines or spaces with single ones
    text = re.sub(r'[\r\n]+', '\n', text)
    text = re.sub(r'[ \t]+', ' ', text)
    
    # 4. Strip leading/trailing whitespace
    text = text.strip()
    
    return text

## --- Core Extraction Functions (Updated to accept language) ---

def extract_text_from_image(image_file, lang_code):
    """
    Uses Tesseract OCR to extract text from an image, using the specified language.
    """
    try:
        img = Image.open(image_file)
        # Pass the language code to image_to_string
        extracted_text = pytesseract.image_to_string(img, lang=lang_code)
        return extracted_text
    except pytesseract.TesseractNotFoundError:
        st.error(
            "Tesseract is not installed or not in your PATH. "
            "Please install the Tesseract OCR engine."
        )
        return ""
    except Exception as e:
        st.error(f"An error occurred during image processing: {e}")
        return ""


def extract_text_from_pdf(pdf_file):
    """
    Uses pypdf to extract text from an uploaded PDF file.
    Note: pypdf extracts digital text, so language selection is not needed here.
    """
    try:
        reader = pypdf.PdfReader(pdf_file)
        text = ""
        for page_num in range(len(reader.pages)):
            page = reader.pages[page_num]
            text += page.extract_text()
            text += "\n\n--- Page Break ---\n\n" 
        return text
    except Exception as e:
        st.error(f"An error occurred during PDF processing: {e}")
        return ""

## --- Streamlit App Layout ---

def main():
    # 🎨 Streamlit Page Configuration
    st.set_page_config(
        page_title="Enhanced Text Extractor",
        page_icon="📄",
        layout="wide",
        initial_sidebar_state="expanded"
    )

    # 🖼️ Title and Header
    st.title("📄 Enhanced Image & PDF Text Extractor")
    st.markdown("Upload a file (PDF, JPEG, or PNG) and adjust settings in the sidebar.")
    st.markdown("---")

    # ⚙️ Sidebar for Settings (Language and Cleaning)
    st.sidebar.header("Extraction Settings")
    
    # 1. Language Selection (for Images only)
    selected_language_name = st.sidebar.selectbox(
        "Select Text Language (for Image OCR):",
        list(LANGUAGE_MAP.keys()),
        index=0 # Default to English
    )
    language_code = LANGUAGE_MAP[selected_language_name]
    
    st.sidebar.markdown("---")
    
    # 2. Text Cleaning Toggle
    should_clean = st.sidebar.checkbox(
        "Apply Text Cleanup (Recommended)",
        value=True # Default to True
    )
    
    st.sidebar.markdown("---")
    st.sidebar.info("Remember to install the appropriate Tesseract language packs for best results!")

    # ⬆️ File Uploader with Status Bar Feature
    uploaded_file = st.file_uploader(
        "Choose a file...",
        type=["pdf", "jpg", "jpeg", "png"],
        key="file_uploader"
    )

    extracted_text = ""
    
    # Check if a file is uploaded
    if uploaded_file is not None:
        
        # ⏳ Use a progress bar during file handling
        with st.spinner("Processing file... This may take a moment."):
            
            # Determine file type and call the correct extraction function
            file_extension = uploaded_file.name.split('.')[-1].lower()
            
            # --- Extraction Logic ---
            if file_extension == 'pdf':
                st.info(f"File uploaded: **{uploaded_file.name}**. Extracting digital text...")
                extracted_text = extract_text_from_pdf(uploaded_file)
                
            elif file_extension in ['jpg', 'jpeg', 'png']:
                st.info(f"File uploaded: **{uploaded_file.name}**. Performing OCR (Language: **{selected_language_name}**)...")
                # Call the image function with the selected language code
                extracted_text = extract_text_from_image(uploaded_file, language_code)
                
            else:
                st.error("Unsupported file type.")
                
            # --- Cleaning Logic ---
            if extracted_text and should_clean:
                st.info("Applying text cleanup...")
                extracted_text = clean_extracted_text(extracted_text)

        # --- Display Results and Download Feature ---
        if extracted_text:
            st.success("✅ Text Extraction Complete!")

            # 📝 Extracted Text Display
            st.subheader("Extracted Text Content")
            st.text_area(
                "Read the final extracted text here:",
                extracted_text,
                height=400,
                key="extracted_text_area"
            )

            # 📥 Download Button for the cleaned/extracted text
            st.subheader("Download Extracted Text")
            
            text_bytes = extracted_text.encode('utf-8')

            st.download_button(
                label="Download Text File (.txt)",
                data=text_bytes,
                file_name=f"{os.path.splitext(uploaded_file.name)[0]}_extracted.txt",
                mime="text/plain"
            )
            
            st.balloons() # Fun Streamlit feature on success

    else:
        # Display when no file is uploaded
        st.info("Awaiting file upload. Please use the sidebar to adjust settings.")

if __name__ == "__main__":
    main()